name: datadriven
dependencies:
- python=3.8.5
- pip=19.1.1
- scipy=1.5.4
- pandas=1.1.4
- pip:
  - ray==1.0.0
  - joblib==0.17.0
  - keras==2.4.3
  - scikit-learn==0.23.2
  - scikit-optimize==0.8.1
  - tensorboard==2.3.0
  - tensorflow==2.3.1
  - tensorflow-estimator==2.3.0
  - microsoft-bonsai-api==0.1.2
  - bonsai-cli==1.0.4
  - pyyaml==5.3.1
  - h5py==2.10.0
  - nbgrader==0.6.1
